# Generated by Django 4.1.3 on 2022-12-03 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=None)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=10000)),
                ('category', models.CharField(blank=True, choices=[('Autre', 'Autre'), ('Immobilier', 'Immobilier'), ('Automobile', 'Automobile'), ('Alimentation', 'Alimentation'), ('Electronique', 'Electronique')], max_length=80, null=True)),
                ('type_immobilier', models.CharField(blank=True, choices=[('Maison', 'Maisson'), ('Appartement', 'Appartement'), ('Location', 'Location'), ('Bureaux', 'Bureaux')], max_length=50, null=True)),
                ('type_automobile', models.CharField(blank=True, choices=[('Neuf', 'Neuf'), ('Occassion', 'Ocassion'), ('Ancien', 'Ancien')], max_length=50, null=True)),
                ('area', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
