# Generated by Django 4.1.3 on 2022-11-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_multipleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='images',
            field=models.FileField(upload_to='static/images'),
        ),
    ]
