# Generated by Django 4.1.3 on 2023-02-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='category',
            field=models.CharField(blank=True, choices=[('Autre', 'Autre'), ('Immobilier', 'Immobilier'), ('Automobile', 'Automobile'), ('Alimentation', 'Alimentation'), ('Electronique', 'Electronique')], max_length=80, null=True),
        ),
    ]
