# Generated by Django 4.1.3 on 2023-02-07 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_favoritepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_entered', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('Autre', 'Autre'), ('Immobilier', 'Immobilier'), ('Automobile', 'Automobile'), ('Alimentation', 'Alimentation'), ('Electronique', 'Electronique')], max_length=80, null=True)),
                ('search_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
